source 'http://rubygems.org'
gem 'activesupport'
gem 'capybara'
gem 'cucumber'
gem 'hashie'
gem 'headless'
gem 'httparty'
# gem 'img_analyzer', :git => "ssh://git@github.com:tlontro/img-analyzer.git"
gem 'img_analyzer', :git => "https://github.com/tlontro/img-analyzer.git"
gem 'json'
gem 'jsonpath'
gem 'nokogiri'
gem 'pry-byebug'
gem 'rake'
gem 'random_data'
gem 'require_all'
gem 'rspec'
gem 'selenium-webdriver'
gem 'uuid'
